name: SGHub
version: 1.0.0
main: fr.skygames.sghub.Main
authors: [ "FullGreen_" ]
description: SkyGames Hub
website: https://skygames.fr
depend:
  - LuckPerms
commands:
  bcommand:
    description: Bungee command
    usage: /bcommand <server>
    aliases: [ "b" ]

permissions:
  sg.break:
    description: Allows players to break blocks in SGHub.
    default: op
